# Configuração do DataSource (PostgreSQL no Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/event_engine_db
spring.datasource.username=postgres
spring.datasource.password=postgres_password
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate e JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
